version: "3.9"

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    networks:
      - ollama-net
    volumes:
      - ollama_data:/root/.ollama

  chatbot:
    build: .
    container_name: chatbot
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434
    networks:
      - ollama-net
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chatbot.rule=Host(`chatbot.devscluster.com`)"
      - "traefik.http.routers.chatbot.entrypoints=web"
      - "traefik.http.services.chatbot.loadbalancer.server.port=8000"

networks:
  web:
    external: true
  ollama-net:
    driver: bridge

volumes:
  ollama_data: